### ISSUE TITLE
Discarded invalid parameter 'contexts'

### ISSUE THREAD

**Issue by changxiangzhong** [joshdholtz/Sentry-Android#101]
We are using the 1.5.0 version of sentry-android with a 8.1.2 local sentry instance. I got this error while logging a debug level log. Do you have any idea on what went wrong here?

Discarded invalid parameter 'contexts'
{
  "name": "contexts"
}

**Comment by joshdholtz** [comment]
@changxiangzhong The `contexts` attribute was added in version `8.6.0` of Sentry - https://github.com/getsentry/sentry/releases/tag/8.6.0. You may need to either use an older version or upgrade your local instance for now.

We _could_ put some sort of special use case in for this in the library but we don't want to get into the habit of supporting things of that nature since it makes maintaining more work 😇

**Comment by changxiangzhong** [comment]
@joshdholtz Thanks for your reply. Do you have a recommended android-sentry version to match sentry 8.1.2?

**Comment by joshdholtz** [comment]
@changxiangzhong I think `1.4.1` should do it for you! If it doesn't let me know and we can maybe sneak in a fix for contexts just this one time 😇 ... But if `1.4.1` works that would be 👌

**Comment by changxiangzhong** [comment]
@joshdholtz Works like a magic! Thank you.

**Comment by joshdholtz** [comment]
@changxiangzhong Great! Let me know if you need anything else ✊
