### ISSUE TITLE
Unicode Decode errors

### ISSUE THREAD

**Issue by halldorbjarni** [joshdholtz/Sentry-Android#20]
Some events aren't getting sent from my android app, possibly because there are strings in Icelandic in the app?

`SendEvent - 403 Bad data reconstructing object (UnicodeDecodeError, 'utf8' codec can't decode byte 0xf3 in position 5: invalid continuation `

The Ruby client seems to have had similar [problems](https://github.com/getsentry/raven-ruby/issues/71). I will look into this, just wanted to let you know :)
Btw fantastic work on the client.

**Comment by Dellkan** [comment]
Just stumbled across this issue.

The message is from Sentry, yes, but it complain because you are sending the data in ISO-8859-1, not UTF-8.

https://github.com/joshdholtz/Sentry-Android/blob/master/src/com/joshdholtz/sentry/Sentry.java#L427

should be changed to 
```java
httpPost.setEntity(new StringEntity(request.getRequestData(), "utf-8"));
```

(StringEntity defaults to ISO-8859-1 if not explicitly overwritten)

**Comment by joshdholtz** [comment]
@Dellkan Thanks! I didn't not know that :innocent: I will work on getting that change put in there :ok_hand:
