### ISSUE TITLE
no Message, no Stacktrace logged

### ISSUE THREAD

**Issue by splitbrain** [joshdholtz/Sentry-Android#25]
I just started playing with this library (with a selfhosted Sentry). To test it I simply created a NullPointer exception. An event is logged to Sentry correctly, but it is missing crucial information:

![sentry](https://cloud.githubusercontent.com/assets/86426/7416528/5d3c1a34-ef60-11e4-8d62-065ded06080b.png)

As you can see, all I get is the class name and line number where the original error occurred. But neither the exception's message nor the stacktrace is available. Is this simply not supported or did I do something wrong? (I didn't add anything beyond the Sentry.init() call).

**Comment by joshdholtz** [comment]
@splitbrain Are you able to get more information if you use getsentry.com?

**Comment by splitbrain** [comment]
I will try on Monday. Meanwhile I got some more info. We had some "real" exception in our app which did got logged with a stacktrace intact. The difference was, that this exception just killed one activity but not the whole app itself, so the error could be sent directly to Sentry. The one I created above killed the whole app and the exception only got sent when restarting the app.

**Comment by joshdholtz** [comment]
@splitbrain Going through and cleaning up issues and things :blush: Were you able to figure out why the null pointer wasn't sending up any sort of stack trace? It should be getting sent up with a stacktrace.

And to answer your other questions, the exceptions do get sent up to Sentry when the app starts up again because there is not enough time to execute a successful request when the app is being killed.

Thanks!

**Comment by splitbrain** [comment]
Sorry, I never investigated any further. I close this assuming it was an error on my end and will reopen should I have more details some day.
